baseURL = "https://debamitro.github.io"
languageCode = "en-us"
title = "Home page of Debamitro Chakraborti"
publishDir = "../"
disableKinds = ["sitemap","taxonomy","taxonomyTerm"]

[markup.goldmark.renderer]
unsafe = true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4
    wrapperClass = 'highlight'