baseURL = "https://debamitro.github.io"
languageCode = "en-us"
title = "Home page of Debamitro Chakraborti"
publishDir = "../"
disableKinds = ["sitemap","taxonomy","taxonomyTerm"]

[markup.goldmark.renderer]
unsafe = true
